### ISSUE TITLE
Рефакторинг на функции

### ISSUE THREAD

**Issue by solonrome** [Grisha-OK/Github-for-me-#3]
Предлагаю переписать код всех 7 действий в виде функций. И вызывать эти функции в обработчике меню.
Так же предлагаю переписать обработчие меню на switch case

Мотивация: Улучишить читаемость кода. Попрактиковаться с функциями.

**Comment by Grisha-OK** [comment]
А что-такое switch case

**Comment by solonrome** [comment]
Туплю, в питоне же нет switch case. Отменяем этот пункт. )
А вообще это более красивый аналог elif
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/switch
