### ISSUE TITLE
Добавить логирование операций

### ISSUE THREAD

**Issue by solonrome** [Grisha-OK/Github-for-me-#4]
Нужно сделать механизм логирования операций изменяющих данные в отдельный файл transaction.log
В лог нужно записать:
- дата и время
- тип операции
- номер счета
- что было
- что изменилось

Мотивация: Нужно обеспечить возможность восстановления информации об операциях (хотя бы вручную) в случае некорректной работы программы или ручных вмешательств в базу.

**Comment by Grisha-OK** [comment]
Так, вот мой план действий:

1. Cделать функцию которая будет принимать аргументы (тип операции, номер счета, что было ,что изменилось) а так же записывать дата и время, тип операции, номер счета, что было, что изменилось, а вызов этой функции будет в функциях которые отвечают за действия в меню они-же будут давать ей нужные аргументы.
2. Как-раз токи реализовать вписывание времени и даты.

Вообще получится ли сделать лог данных через функцию?  

@solonrome
