### ISSUE TITLE
Скрипт Data_base_extras ломает базу

### ISSUE THREAD

**Issue by solonrome** [Grisha-OK/Github-for-me-#9]
Скрипт открывает файл в режиме append и ломает структуру базы. Хорошо бы сделать чтобы он открывал содержимое базы и дописывал тестовые данные в неё, либо написать коментарий с инструкцией что его нельзя запускать если файл базу уже создан.

**Comment by Grisha-OK** [comment]
Ты же понимаешь что я пойду по простому путь, и просто сделаю комент. если ты меня конечно не остановишь

**Comment by solonrome** [comment]
Я ни на чем не настаиваю, оба варианта более менее решают проблему и оба не идеальны.
